[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[client]
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#0C4A6E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"
